export enum ProductTCP {
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  FIND_PRODUCTS = 'FIND_PRODUCTS',
  FIND_PRODUCT = 'FIND_PRODUCT',
  EDIT_PRODUCT = 'EDIT_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  DELETE_PRODUCT_IMAGE='DELETE_PRODUCT_IMAGE',
  CREATE_PRODUCT_IMAGES='CREATE_PRODUCT_IMAGES',
  FIND_PRODUCTS_BY_IDS = 'FIND_PRODUCTS_BY_IDS0,'
}
